/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.meaw.view;
import br.inatel.meaw.controller.MySQLConnection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.inatel.meaw.model.DAO.UserPremiumDAO;
import br.inatel.meaw.model.Musica;
import br.inatel.meaw.model.Playlist;
import br.inatel.meaw.utils.Constants;
        
/**
 *
 * @author julia e rafaela
 */
public class Playlistview extends javax.swing.JFrame {
    UserPremiumDAO userpremiumcomumDAO = new UserPremiumDAO();
    MySQLConnection mySQLConnection = new MySQLConnection();
    DefaultTableModel dtmP;
    DefaultTableModel dtmM;
    int idUsuario;
    int countMusic = 0;
    int totalMusic = 0;
    /**
     * Creates new form FramaInicil
     */
    
    public Playlistview() {
        initComponents();
        this.setTitle(Constants.TITLE);
        this.setLocationRelativeTo(null);
        mySQLConnection.connectMySQL();      
        idUsuario = Constants.login;
        dtmP = (DefaultTableModel) tablePlaylist.getModel();
        dtmM = (DefaultTableModel) tableMusica.getModel(); 
        tablePlay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelInicial = new javax.swing.JPanel();
        painelCadastro = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePlaylist = new javax.swing.JTable();
        btnDeletarPlay = new javax.swing.JButton();
        idDelete = new javax.swing.JTextField();
        btnReproduzirPlay = new javax.swing.JButton();
        btnCriarPlay = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableMusica = new javax.swing.JTable();
        reproduzirMusica = new javax.swing.JTextField();
        btnProximo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        title2 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        btnAbrirMusicas = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jScrollPane1.setViewportView(jEditorPane1);

        jScrollPane3.setViewportView(jTextPane1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInicial.setBackground(new java.awt.Color(169, 210, 254));
        panelInicial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelInicial.setForeground(new java.awt.Color(169, 210, 254));

        painelCadastro.setBackground(new java.awt.Color(169, 210, 254));
        painelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 2, true), "Minhas Playlists", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(247, 37, 133))); // NOI18N
        painelCadastro.setForeground(new java.awt.Color(247, 37, 133));
        painelCadastro.setName("Cadastro"); // NOI18N

        tablePlaylist.setBackground(new java.awt.Color(169, 210, 254));
        tablePlaylist.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tablePlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Musica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePlaylist.setGridColor(new java.awt.Color(255, 255, 255));
        tablePlaylist.setSelectionBackground(new java.awt.Color(114, 9, 183));
        jScrollPane4.setViewportView(tablePlaylist);

        btnDeletarPlay.setBackground(new java.awt.Color(169, 210, 254));
        btnDeletarPlay.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDeletarPlay.setForeground(new java.awt.Color(247, 37, 133));
        btnDeletarPlay.setText("Deletar");
        btnDeletarPlay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDeletarPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletarPlay.setOpaque(false);
        btnDeletarPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarPlayActionPerformed(evt);
            }
        });

        idDelete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idDelete.setForeground(new java.awt.Color(114, 9, 183));
        idDelete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 3, true));

        btnReproduzirPlay.setBackground(new java.awt.Color(169, 210, 254));
        btnReproduzirPlay.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnReproduzirPlay.setForeground(new java.awt.Color(247, 37, 133));
        btnReproduzirPlay.setText("Reproduzir");
        btnReproduzirPlay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnReproduzirPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReproduzirPlay.setOpaque(false);
        btnReproduzirPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproduzirPlayActionPerformed(evt);
            }
        });

        btnCriarPlay.setBackground(new java.awt.Color(169, 210, 254));
        btnCriarPlay.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCriarPlay.setForeground(new java.awt.Color(247, 37, 133));
        btnCriarPlay.setText("Criar");
        btnCriarPlay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCriarPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCriarPlay.setOpaque(false);
        btnCriarPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addComponent(btnReproduzirPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCriarPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnDeletarPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReproduzirPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCriarPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletarPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(169, 210, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 2, true), "Reproduzir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(247, 37, 133))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(247, 37, 133));

        tableMusica.setBackground(new java.awt.Color(169, 210, 254));
        tableMusica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Artista", "Genero", "Tempo Duração", "Ano"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMusica.setGridColor(new java.awt.Color(255, 255, 255));
        tableMusica.setSelectionBackground(new java.awt.Color(114, 9, 183));
        jScrollPane5.setViewportView(tableMusica);

        reproduzirMusica.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        reproduzirMusica.setForeground(new java.awt.Color(114, 9, 183));
        reproduzirMusica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        reproduzirMusica.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        btnProximo.setBackground(new java.awt.Color(169, 210, 254));
        btnProximo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnProximo.setForeground(new java.awt.Color(247, 37, 133));
        btnProximo.setText(">>");
        btnProximo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnAnterior.setBackground(new java.awt.Color(169, 210, 254));
        btnAnterior.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(247, 37, 133));
        btnAnterior.setText("<<");
        btnAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(reproduzirMusica, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnterior)
                .addGap(199, 199, 199)
                .addComponent(btnProximo)
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo)
                    .addComponent(btnAnterior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reproduzirMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        btnSair.setBackground(new java.awt.Color(255, 51, 51));
        btnSair.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSair.setText("X");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        title2.setBackground(new java.awt.Color(247, 37, 133));
        title2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(247, 37, 133));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Playlist");
        title2.setToolTipText("");
        title2.setFocusable(false);
        title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        title1.setBackground(new java.awt.Color(169, 210, 254));
        title1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(247, 37, 133));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("MEAW");
        title1.setToolTipText("");
        title1.setFocusable(false);
        title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        icon2.setBackground(new java.awt.Color(247, 37, 133));
        icon2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        icon2.setForeground(new java.awt.Color(247, 37, 133));
        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/meaw/images/cat-black-face.png"))); // NOI18N
        icon2.setToolTipText("");
        icon2.setFocusable(false);
        icon2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        icon1.setBackground(new java.awt.Color(169, 210, 254));
        icon1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        icon1.setForeground(new java.awt.Color(169, 210, 254));
        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/meaw/images/cat-black-face.png"))); // NOI18N
        icon1.setToolTipText("");
        icon1.setFocusable(false);
        icon1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAbrirMusicas.setBackground(new java.awt.Color(169, 210, 254));
        btnAbrirMusicas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAbrirMusicas.setForeground(new java.awt.Color(247, 37, 133));
        btnAbrirMusicas.setText("Musicas");
        btnAbrirMusicas.setBorder(null);
        btnAbrirMusicas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrirMusicas.setOpaque(false);
        btnAbrirMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirMusicasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicialLayout = new javax.swing.GroupLayout(panelInicial);
        panelInicial.setLayout(panelInicialLayout);
        panelInicialLayout.setHorizontalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnAbrirMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnSair)
                        .addGap(40, 40, 40))))
        );
        panelInicialLayout.setVerticalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSair)
                                .addComponent(btnAbrirMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReproduzirPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproduzirPlayActionPerformed
        
        String idPlay;
        String nomeMusica;
        int linhaR = 0;
        int linha = tablePlaylist.getSelectedRow();
        
        if (linha != -1){
            idPlay = tablePlaylist.getValueAt(linha, 0).toString();
                       
            dtmM.setRowCount(0);               
            for (Musica musica : userpremiumcomumDAO.listarMusicaPlay(mySQLConnection, idPlay)){   
                dtmM.addRow(new Object[]{
                musica.getIdMusica(), musica.getNomeMusica(), musica.getnomeArtista(), musica.getGenero(), musica.getTempoDuracao(), musica.getAno()
            });
                
            totalMusic = dtmM.getRowCount();            
            String nomeMusicPlaying = tableMusica.getValueAt(countMusic, 1).toString();
            reproduzirMusica.setText(nomeMusicPlaying);
            }    
        }else  JOptionPane.showMessageDialog(this, "Selecione uma linha!", "ERRO!", JOptionPane.WARNING_MESSAGE);      
    }//GEN-LAST:event_btnReproduzirPlayActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Cadastroview cadastroView = new Cadastroview();
        this.dispose();
        cadastroView.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnDeletarPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarPlayActionPerformed
       try{
           int id = Integer.parseInt(idDelete.getText());
           userpremiumcomumDAO.deletarPlaylist(mySQLConnection, id);
           tablePlay();
           limparCampos();
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Insira um id valido!", "ERRO!", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnDeletarPlayActionPerformed

    private void btnCriarPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarPlayActionPerformed
        CriarPlaylistView criarplaylistView = new  CriarPlaylistView();
        this.dispose();
        criarplaylistView.setVisible(true);
    }//GEN-LAST:event_btnCriarPlayActionPerformed

    private void btnAbrirMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirMusicasActionPerformed
        Musicaview musicaView = new Musicaview();
        this.dispose();
        musicaView.setVisible(true);
    }//GEN-LAST:event_btnAbrirMusicasActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        countMusic ++;
        if(countMusic >= totalMusic) countMusic = 0;
        String nomeMusicPlaying = tableMusica.getValueAt(countMusic, 1).toString();
        reproduzirMusica.setText(nomeMusicPlaying);
        
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        countMusic --;
        if(countMusic < 0) countMusic = totalMusic-1;
        String nomeMusicPlaying = tableMusica.getValueAt(countMusic, 1).toString();
        reproduzirMusica.setText(nomeMusicPlaying);
    }//GEN-LAST:event_btnAnteriorActionPerformed
    
    private void limparCampos() {
        idDelete.setText(" ");
    }
    
     private void tablePlay(){
        dtmP.setRowCount(0);
                
        for (Playlist playlist : userpremiumcomumDAO.listarPlaylist(mySQLConnection,idUsuario)){ 
            userpremiumcomumDAO.quantidadeMusica(mySQLConnection, playlist.getIdPlaylist());
            System.out.println(playlist.getIdPlaylist());
            System.out.println(playlist.getQtdMusicasPlay());
            dtmP.addRow(new Object[]{
                playlist.getIdPlaylist(), playlist.getNomePlay(), playlist.getQtdMusicasPlay()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirMusicas;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCriarPlay;
    private javax.swing.JButton btnDeletarPlay;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnReproduzirPlay;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JTextField idDelete;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JPanel panelInicial;
    private javax.swing.JTextField reproduzirMusica;
    private javax.swing.JTable tableMusica;
    private javax.swing.JTable tablePlaylist;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables

    
}
