/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.meaw.view;

import br.inatel.meaw.controller.MySQLConnection;
import br.inatel.meaw.exception.CampoVazioException;
import br.inatel.meaw.exception.EmailInvalidoException;
import br.inatel.meaw.exception.UsuarioExistenteException;
import javax.swing.JOptionPane;
import br.inatel.meaw.model.DAO.GerenciadorDAO;
import br.inatel.meaw.model.DAO.UserComumDAO;
import br.inatel.meaw.model.DAO.UserPremiumDAO;
import br.inatel.meaw.model.DAO.UsuarioDAO;
import br.inatel.meaw.model.Gerenciador;
import br.inatel.meaw.model.UserComum;
import br.inatel.meaw.model.UserPremium;
import br.inatel.meaw.model.Usuario;
import br.inatel.meaw.utils.Constants;

/**
 *
 * @author julia e rafaela
 */
public class Cadastroview extends javax.swing.JFrame {
    UsuarioDAO userDAO;
    Usuario user;
    UsuarioDAO usuarioAdd = new UsuarioDAO();
    MySQLConnection mySQLConnection = new MySQLConnection();
    
    /**
     * Creates new form FramaInicil
     */
    public Cadastroview() {
        initComponents();
        this.setTitle(Constants.TITLE);
        this.setLocationRelativeTo(null);
        mySQLConnection.connectMySQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        buttonGroupUser = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        panelInicial = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        painelCadastro = new javax.swing.JPanel();
        jLabel_NOME = new javax.swing.JLabel();
        jLabel_EMAIL = new javax.swing.JLabel();
        entradanomeUsuario = new javax.swing.JTextField();
        entradaemailUsuario = new javax.swing.JTextField();
        jLabel_SENHA = new javax.swing.JLabel();
        entradasenhaUsuario = new javax.swing.JTextField();
        radioGerenciador = new javax.swing.JRadioButton();
        radioUsuario = new javax.swing.JRadioButton();
        radioPremium = new javax.swing.JRadioButton();
        btnCadastrarUsuario = new javax.swing.JButton();
        panelLogin = new javax.swing.JPanel();
        jLabel_LOGINEMAIL = new javax.swing.JLabel();
        loginemailUsuario = new javax.swing.JTextField();
        jLabel_LOGINSENHA = new javax.swing.JLabel();
        loginsenhaUsuario = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jScrollPane1.setViewportView(jEditorPane1);

        jScrollPane3.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInicial.setBackground(new java.awt.Color(169, 210, 254));
        panelInicial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelInicial.setForeground(new java.awt.Color(255, 255, 255));

        icon.setBackground(new java.awt.Color(204, 0, 153));
        icon.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        icon.setForeground(new java.awt.Color(204, 0, 153));
        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/meaw/images/cat-black-face.png"))); // NOI18N
        icon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        icon.setFocusable(false);
        icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        painelCadastro.setBackground(new java.awt.Color(169, 210, 254));
        painelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 2, true), "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(247, 37, 133))); // NOI18N
        painelCadastro.setForeground(new java.awt.Color(247, 37, 133));
        painelCadastro.setName("Cadastro"); // NOI18N

        jLabel_NOME.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_NOME.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_NOME.setText("Nome:");

        jLabel_EMAIL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_EMAIL.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_EMAIL.setText("E-mail:");

        entradanomeUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        entradanomeUsuario.setForeground(new java.awt.Color(114, 9, 183));
        entradanomeUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        entradaemailUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        entradaemailUsuario.setForeground(new java.awt.Color(114, 9, 183));
        entradaemailUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        jLabel_SENHA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_SENHA.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_SENHA.setText("Senha:");

        entradasenhaUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        entradasenhaUsuario.setForeground(new java.awt.Color(114, 9, 183));
        entradasenhaUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel_SENHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradasenhaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NOME)
                            .addComponent(jLabel_EMAIL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entradanomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(entradaemailUsuario))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NOME)
                    .addComponent(entradanomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EMAIL)
                    .addComponent(entradaemailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SENHA)
                    .addComponent(entradasenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        radioGerenciador.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupUser.add(radioGerenciador);
        radioGerenciador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioGerenciador.setForeground(new java.awt.Color(247, 37, 133));
        radioGerenciador.setText("Gerenciador");
        radioGerenciador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radioGerenciador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        radioUsuario.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupUser.add(radioUsuario);
        radioUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioUsuario.setForeground(new java.awt.Color(247, 37, 133));
        radioUsuario.setText("Usuário");
        radioUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radioUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        radioPremium.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupUser.add(radioPremium);
        radioPremium.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioPremium.setForeground(new java.awt.Color(247, 37, 133));
        radioPremium.setText("Usuário Premium");
        radioPremium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radioPremium.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnCadastrarUsuario.setBackground(new java.awt.Color(169, 210, 254));
        btnCadastrarUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadastrarUsuario.setForeground(new java.awt.Color(247, 37, 133));
        btnCadastrarUsuario.setText("Cadastrar");
        btnCadastrarUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCadastrarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });

        panelLogin.setBackground(new java.awt.Color(169, 210, 254));
        panelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 2, true), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(247, 37, 133))); // NOI18N
        panelLogin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        jLabel_LOGINEMAIL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_LOGINEMAIL.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_LOGINEMAIL.setText("E-mail:");

        loginemailUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        loginemailUsuario.setForeground(new java.awt.Color(247, 37, 133));
        loginemailUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        jLabel_LOGINSENHA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_LOGINSENHA.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_LOGINSENHA.setText("Senha:");

        loginsenhaUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        loginsenhaUsuario.setForeground(new java.awt.Color(247, 37, 133));
        loginsenhaUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel_LOGINEMAIL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginemailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel_LOGINSENHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginsenhaUsuario)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LOGINEMAIL)
                    .addComponent(loginemailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LOGINSENHA)
                    .addComponent(loginsenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnLogin.setBackground(new java.awt.Color(169, 210, 254));
        btnLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(247, 37, 133));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setOpaque(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        title.setBackground(new java.awt.Color(247, 37, 133));
        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(247, 37, 133));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("MEAW");
        title.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        title.setFocusable(false);
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSair.setBackground(new java.awt.Color(204, 204, 255));
        btnSair.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSair.setText("X");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicialLayout = new javax.swing.GroupLayout(panelInicial);
        panelInicial.setLayout(panelInicialLayout);
        panelInicialLayout.setHorizontalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelInicialLayout.createSequentialGroup()
                                .addComponent(radioGerenciador, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelInicialLayout.createSequentialGroup()
                                        .addComponent(radioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialLayout.createSequentialGroup()
                                        .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(138, 138, 138))))
                            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair)))
                .addGap(0, 24, Short.MAX_VALUE))
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelInicialLayout.setVerticalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(1, 1, 1)
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioGerenciador)
                        .addComponent(radioUsuario)))
                .addGap(18, 18, 18)
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair)))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        
        String tipo =  null;
        
        if(radioGerenciador.isSelected()){
            user = new Gerenciador();
            userDAO = new GerenciadorDAO();            
        }else if(radioUsuario.isSelected()){
            user = new UserComum();
            userDAO = new UserComumDAO();
        }else if(radioPremium.isSelected()){
            user = new UserPremium();
            userDAO = new UserPremiumDAO();
        }else{
            JOptionPane.showMessageDialog(this, "Selecione o tipo.","Cadastro", JOptionPane.ERROR_MESSAGE);
        }
        
        try{
            user.setNomeUsuario(entradanomeUsuario.getText());
            user.setEmail(entradaemailUsuario.getText());
            user.setSenha(entradasenhaUsuario.getText());
            userDAO.existeUsuario(mySQLConnection, user);
            userDAO.inserirUsuario(mySQLConnection, user);
            limparCampos();
        }catch (EmailInvalidoException e){
            JOptionPane.showMessageDialog(this, "E-mail invalido", tipo, JOptionPane.ERROR_MESSAGE); 
        }catch(CampoVazioException e){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos", "Cadastro", JOptionPane.ERROR_MESSAGE);
        }catch (UsuarioExistenteException e){
            JOptionPane.showMessageDialog(this, "E-mail de usuario já existente", "Cadastro", JOptionPane.ERROR_MESSAGE); 
        }   
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        Usuario userLogin = new Usuario();
        
        String email = loginemailUsuario.getText();
        String senha = loginsenhaUsuario.getText();
        
        userLogin = usuarioAdd.buscarUsuario(mySQLConnection, email, senha);
        int id = userLogin.getIdUsuario();
        Constants.login = id;
        
        if(id!= 0){
            int tipo = userLogin.getIdTipoUsuario();
            switch(tipo){
                case 101: 
                    Gerenciadorview gerenciadorView = new Gerenciadorview();
                    this.dispose();
                    gerenciadorView.setVisible(true); 
                    break;
                case 202:
                    Musicaview musicaView = new Musicaview();
                    this.dispose();
                    musicaView.setVisible(true);
                    break;
                case 303:
                    Playlistview playlistView = new Playlistview();
                    this.dispose();
                    playlistView.setVisible(true);
                    break;
            }
            limparCampos();            
        }
        else JOptionPane.showMessageDialog(this, "Invalido", "Login", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        mySQLConnection.disconectMySQL();
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void limparCampos() {
        entradanomeUsuario.setText("");
        entradaemailUsuario.setText("");
        entradasenhaUsuario.setText("");
        buttonGroupUser.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroupUser;
    private javax.swing.JTextField entradaemailUsuario;
    private javax.swing.JTextField entradanomeUsuario;
    private javax.swing.JTextField entradasenhaUsuario;
    private javax.swing.JLabel icon;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel_EMAIL;
    private javax.swing.JLabel jLabel_LOGINEMAIL;
    private javax.swing.JLabel jLabel_LOGINSENHA;
    private javax.swing.JLabel jLabel_NOME;
    private javax.swing.JLabel jLabel_SENHA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField loginemailUsuario;
    public javax.swing.JPasswordField loginsenhaUsuario;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JPanel panelInicial;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JRadioButton radioGerenciador;
    private javax.swing.JRadioButton radioPremium;
    private javax.swing.JRadioButton radioUsuario;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    
}
