/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.meaw.view;
import br.inatel.meaw.controller.MySQLConnection;
import br.inatel.meaw.exception.CampoVazioException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.inatel.meaw.model.Musica;
import br.inatel.meaw.model.Artista;
import br.inatel.meaw.model.DAO.ArtistaDAO;
import br.inatel.meaw.model.DAO.GerenciadorDAO;
import br.inatel.meaw.model.Usuario;
import br.inatel.meaw.utils.Constants;
        
/**
 *
 * @author julia e rafaela
 */
public class Gerenciadorview extends javax.swing.JFrame {
    
    Artista artista;
    Musica music = new Musica();
    GerenciadorDAO gerenciadorDAO = new GerenciadorDAO();
    ArtistaDAO artistaDAO = new ArtistaDAO();
    MySQLConnection mySQLConnection = new MySQLConnection();
    DefaultTableModel dtmU;
    DefaultTableModel dtmM;
    
     /**
     * Creates new form FramaInicil
     */
    public Gerenciadorview() {
        initComponents();
        this.setTitle(Constants.TITLE);
        this.setLocationRelativeTo(null);
        mySQLConnection.connectMySQL();
        comboboxArtista();
        
        dtmU = (DefaultTableModel) tableUsuario.getModel();
        dtmM = (DefaultTableModel) tableMusica.getModel();
        tabelaUsuarios();
        tabelaMusica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        buttonGroupGenero = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelInicial = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        painelCadastro = new javax.swing.JPanel();
        jLabel_Artista = new javax.swing.JLabel();
        emusicaID = new javax.swing.JTextField();
        jLabel_Genero = new javax.swing.JLabel();
        eidMusica = new javax.swing.JLabel();
        emusicaTempo = new javax.swing.JTextField();
        jLabel_Ano = new javax.swing.JLabel();
        emusicaAno = new javax.swing.JTextField();
        radioPop = new javax.swing.JRadioButton();
        radioMpb = new javax.swing.JRadioButton();
        radioGospel = new javax.swing.JRadioButton();
        jLabel_Tempo = new javax.swing.JLabel();
        radioEletronica = new javax.swing.JRadioButton();
        radioPagode = new javax.swing.JRadioButton();
        radioIndie = new javax.swing.JRadioButton();
        radioRock = new javax.swing.JRadioButton();
        radioSertanejo = new javax.swing.JRadioButton();
        radioHiphop = new javax.swing.JRadioButton();
        comboboxArtista = new javax.swing.JComboBox<>();
        btnCadastrarMusica = new javax.swing.JButton();
        btnAtualizarMusica = new javax.swing.JButton();
        jLabel_NOME = new javax.swing.JLabel();
        emusicaNome = new javax.swing.JTextField();
        panelLogin = new javax.swing.JPanel();
        excluiridMusica = new javax.swing.JTextField();
        btnExcluirMusica = new javax.swing.JButton();
        jLabel_id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUsuario = new javax.swing.JTable();
        btnSelecionarMusica = new javax.swing.JButton();
        idDelete = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableMusica = new javax.swing.JTable();
        btnExcluirUsuario = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        panelLogin1 = new javax.swing.JPanel();
        jLabel_Artista1 = new javax.swing.JLabel();
        comboboxselectArtista = new javax.swing.JComboBox<>();
        jLabel_MUSICAS = new javax.swing.JLabel();
        quantidadeMusica = new javax.swing.JTextField();
        btnQtdArtista = new javax.swing.JButton();
        btnAdiconarArtista = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jScrollPane1.setViewportView(jEditorPane1);

        jScrollPane3.setViewportView(jTextPane1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInicial.setBackground(new java.awt.Color(169, 210, 254));
        panelInicial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelInicial.setForeground(new java.awt.Color(255, 255, 255));

        title2.setBackground(new java.awt.Color(247, 37, 133));
        title2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(247, 37, 133));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Gerenciador");
        title2.setToolTipText("");
        title2.setFocusable(false);
        title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        painelCadastro.setBackground(new java.awt.Color(169, 210, 254));
        painelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 2, true), "Adicionar Musica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(247, 37, 133))); // NOI18N
        painelCadastro.setForeground(new java.awt.Color(247, 37, 133));
        painelCadastro.setName("Cadastro"); // NOI18N

        jLabel_Artista.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Artista.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_Artista.setText("Artista:");

        emusicaID.setEditable(false);
        emusicaID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emusicaID.setForeground(new java.awt.Color(114, 9, 183));
        emusicaID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        jLabel_Genero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Genero.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_Genero.setText("Gênero:");

        eidMusica.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        eidMusica.setForeground(new java.awt.Color(247, 37, 133));
        eidMusica.setText("ID:");

        emusicaTempo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emusicaTempo.setForeground(new java.awt.Color(114, 9, 183));
        emusicaTempo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        jLabel_Ano.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Ano.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_Ano.setText("Ano:");

        emusicaAno.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emusicaAno.setForeground(new java.awt.Color(114, 9, 183));
        emusicaAno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        radioPop.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupGenero.add(radioPop);
        radioPop.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioPop.setForeground(new java.awt.Color(247, 37, 133));
        radioPop.setText("Pop");
        radioPop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        radioPop.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        radioMpb.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupGenero.add(radioMpb);
        radioMpb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioMpb.setForeground(new java.awt.Color(247, 37, 133));
        radioMpb.setText("MPB");
        radioMpb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        radioMpb.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        radioGospel.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupGenero.add(radioGospel);
        radioGospel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioGospel.setForeground(new java.awt.Color(247, 37, 133));
        radioGospel.setText("Gospel");
        radioGospel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        radioGospel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel_Tempo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Tempo.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_Tempo.setText("Tempo Duração:");

        radioEletronica.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupGenero.add(radioEletronica);
        radioEletronica.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioEletronica.setForeground(new java.awt.Color(247, 37, 133));
        radioEletronica.setText("Eletronica");
        radioEletronica.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        radioEletronica.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        radioPagode.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupGenero.add(radioPagode);
        radioPagode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioPagode.setForeground(new java.awt.Color(247, 37, 133));
        radioPagode.setText("Pagode");
        radioPagode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        radioPagode.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        radioIndie.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupGenero.add(radioIndie);
        radioIndie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioIndie.setForeground(new java.awt.Color(247, 37, 133));
        radioIndie.setText("Indie");
        radioIndie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        radioIndie.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        radioRock.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupGenero.add(radioRock);
        radioRock.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioRock.setForeground(new java.awt.Color(247, 37, 133));
        radioRock.setText("Rock");
        radioRock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        radioRock.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        radioSertanejo.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupGenero.add(radioSertanejo);
        radioSertanejo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioSertanejo.setForeground(new java.awt.Color(247, 37, 133));
        radioSertanejo.setText("Sertanejo");
        radioSertanejo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        radioSertanejo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        radioHiphop.setBackground(new java.awt.Color(169, 210, 254));
        buttonGroupGenero.add(radioHiphop);
        radioHiphop.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioHiphop.setForeground(new java.awt.Color(247, 37, 133));
        radioHiphop.setText("Hip Hop");
        radioHiphop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        radioHiphop.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        comboboxArtista.setBackground(new java.awt.Color(169, 210, 254));
        comboboxArtista.setEditable(true);
        comboboxArtista.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        comboboxArtista.setForeground(new java.awt.Color(114, 9, 183));
        comboboxArtista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        btnCadastrarMusica.setBackground(new java.awt.Color(169, 210, 254));
        btnCadastrarMusica.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCadastrarMusica.setForeground(new java.awt.Color(247, 37, 133));
        btnCadastrarMusica.setText("Cadastrar");
        btnCadastrarMusica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCadastrarMusica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarMusica.setOpaque(false);
        btnCadastrarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMusicaActionPerformed(evt);
            }
        });

        btnAtualizarMusica.setBackground(new java.awt.Color(169, 210, 254));
        btnAtualizarMusica.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAtualizarMusica.setForeground(new java.awt.Color(247, 37, 133));
        btnAtualizarMusica.setText("Atualizar");
        btnAtualizarMusica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAtualizarMusica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizarMusica.setOpaque(false);
        btnAtualizarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarMusicaActionPerformed(evt);
            }
        });

        jLabel_NOME.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_NOME.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_NOME.setText("Nome:");

        emusicaNome.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        emusicaNome.setForeground(new java.awt.Color(114, 9, 183));
        emusicaNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel_NOME)
                        .addGap(13, 13, 13)
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                                .addComponent(eidMusica)
                                .addGap(30, 30, 30)
                                .addComponent(emusicaID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(199, 199, 199))
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(emusicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(painelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel_Ano)
                                        .addGap(29, 29, 29)
                                        .addComponent(emusicaAno, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel_Artista)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboboxArtista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 17, Short.MAX_VALUE))))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel_Tempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emusicaTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnCadastrarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel_Genero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(radioPop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioMpb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioIndie, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(radioEletronica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(radioRock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioPagode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radioGospel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioSertanejo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(radioHiphop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnAtualizarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eidMusica)
                    .addComponent(emusicaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Artista)
                            .addComponent(comboboxArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_NOME)))
                    .addComponent(emusicaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Tempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emusicaTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Ano)
                    .addComponent(emusicaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMpb)
                    .addComponent(radioRock)
                    .addComponent(radioSertanejo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPop)
                    .addComponent(jLabel_Genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioEletronica)
                    .addComponent(radioHiphop, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioIndie)
                    .addComponent(radioPagode)
                    .addComponent(radioGospel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelLogin.setBackground(new java.awt.Color(169, 210, 254));
        panelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 2, true), "Excluir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(247, 37, 133))); // NOI18N
        panelLogin.setForeground(new java.awt.Color(247, 37, 133));

        excluiridMusica.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        excluiridMusica.setForeground(new java.awt.Color(114, 9, 183));
        excluiridMusica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        excluiridMusica.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 3, true));

        btnExcluirMusica.setBackground(new java.awt.Color(169, 210, 254));
        btnExcluirMusica.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExcluirMusica.setForeground(new java.awt.Color(247, 37, 133));
        btnExcluirMusica.setText("Excluir");
        btnExcluirMusica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExcluirMusica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirMusica.setOpaque(false);
        btnExcluirMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMusicaActionPerformed(evt);
            }
        });

        jLabel_id.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_id.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_id.setText("ID:");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(excluiridMusica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirMusica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel_id)
                    .addContainerGap(135, Short.MAX_VALUE)))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(excluiridMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluirMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoginLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel_id)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(169, 210, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 2, true), "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(247, 37, 133))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(247, 37, 133));

        tableUsuario.setBackground(new java.awt.Color(169, 210, 254));
        tableUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "E-mail", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsuario.setGridColor(new java.awt.Color(255, 255, 255));
        tableUsuario.setSelectionBackground(new java.awt.Color(114, 9, 183));
        jScrollPane2.setViewportView(tableUsuario);

        btnSelecionarMusica.setBackground(new java.awt.Color(169, 210, 254));
        btnSelecionarMusica.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSelecionarMusica.setForeground(new java.awt.Color(247, 37, 133));
        btnSelecionarMusica.setText("Selecionar");
        btnSelecionarMusica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSelecionarMusica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSelecionarMusica.setOpaque(false);
        btnSelecionarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarMusicaActionPerformed(evt);
            }
        });

        idDelete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        idDelete.setForeground(new java.awt.Color(114, 9, 183));
        idDelete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 3, true));

        tableMusica.setBackground(new java.awt.Color(169, 210, 254));
        tableMusica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Artista", "Genero", "Tempo", "Ano"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMusica.setGridColor(new java.awt.Color(255, 255, 255));
        tableMusica.setSelectionBackground(new java.awt.Color(114, 9, 183));
        jScrollPane4.setViewportView(tableMusica);

        btnExcluirUsuario.setBackground(new java.awt.Color(169, 210, 254));
        btnExcluirUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExcluirUsuario.setForeground(new java.awt.Color(247, 37, 133));
        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExcluirUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirUsuario.setOpaque(false);
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelecionarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSair.setBackground(new java.awt.Color(255, 51, 51));
        btnSair.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSair.setText("X");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        title.setBackground(new java.awt.Color(247, 37, 133));
        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(247, 37, 133));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("MEAW");
        title.setToolTipText("");
        title.setFocusable(false);
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        icon2.setBackground(new java.awt.Color(247, 37, 133));
        icon2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        icon2.setForeground(new java.awt.Color(247, 37, 133));
        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/meaw/images/cat-black-face.png"))); // NOI18N
        icon2.setToolTipText("");
        icon2.setFocusable(false);
        icon2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        icon1.setBackground(new java.awt.Color(247, 37, 133));
        icon1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        icon1.setForeground(new java.awt.Color(247, 37, 133));
        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/inatel/meaw/images/cat-black-face.png"))); // NOI18N
        icon1.setToolTipText("");
        icon1.setFocusable(false);
        icon1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panelLogin1.setBackground(new java.awt.Color(169, 210, 254));
        panelLogin1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 2, true), "Artista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(247, 37, 133))); // NOI18N
        panelLogin1.setForeground(new java.awt.Color(247, 37, 133));

        jLabel_Artista1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Artista1.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_Artista1.setText("Nome:");

        comboboxselectArtista.setBackground(new java.awt.Color(169, 210, 254));
        comboboxselectArtista.setEditable(true);
        comboboxselectArtista.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        comboboxselectArtista.setForeground(new java.awt.Color(114, 9, 183));
        comboboxselectArtista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 1, true));

        jLabel_MUSICAS.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_MUSICAS.setForeground(new java.awt.Color(247, 37, 133));
        jLabel_MUSICAS.setText("Musica:");

        quantidadeMusica.setEditable(false);
        quantidadeMusica.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        quantidadeMusica.setForeground(new java.awt.Color(114, 9, 183));
        quantidadeMusica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantidadeMusica.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 37, 133), 3, true));

        btnQtdArtista.setBackground(new java.awt.Color(169, 210, 254));
        btnQtdArtista.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnQtdArtista.setForeground(new java.awt.Color(247, 37, 133));
        btnQtdArtista.setText("Ir");
        btnQtdArtista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQtdArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQtdArtistaActionPerformed(evt);
            }
        });

        btnAdiconarArtista.setBackground(new java.awt.Color(169, 210, 254));
        btnAdiconarArtista.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAdiconarArtista.setForeground(new java.awt.Color(247, 37, 133));
        btnAdiconarArtista.setText("Novo");
        btnAdiconarArtista.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAdiconarArtista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdiconarArtista.setOpaque(false);
        btnAdiconarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdiconarArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLogin1Layout = new javax.swing.GroupLayout(panelLogin1);
        panelLogin1.setLayout(panelLogin1Layout);
        panelLogin1Layout.setHorizontalGroup(
            panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Artista1)
                    .addComponent(jLabel_MUSICAS))
                .addGap(18, 18, 18)
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogin1Layout.createSequentialGroup()
                        .addComponent(btnAdiconarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLogin1Layout.createSequentialGroup()
                        .addComponent(comboboxselectArtista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelLogin1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(quantidadeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnQtdArtista)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelLogin1Layout.setVerticalGroup(
            panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Artista1)
                    .addComponent(comboboxselectArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MUSICAS)
                    .addComponent(quantidadeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQtdArtista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnAdiconarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelInicialLayout = new javax.swing.GroupLayout(panelInicial);
        panelInicial.setLayout(panelInicialLayout);
        panelInicialLayout.setHorizontalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInicialLayout.createSequentialGroup()
                                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInicialLayout.createSequentialGroup()
                                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(panelLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGap(0, 167, Short.MAX_VALUE)
                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSair))
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInicialLayout.setVerticalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(icon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelInicialLayout.createSequentialGroup()
                                .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInicialLayout.createSequentialGroup()
                        .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarMusicaActionPerformed
        int linha = tableMusica.getSelectedRow();
        if (linha != -1){
           String idMusica = tableMusica.getValueAt(linha, 0).toString();
           String nomeMusica = tableMusica.getValueAt(linha, 1).toString();
           String nomeArtista = tableMusica.getValueAt(linha, 2).toString();
           String generoMusica = tableMusica.getValueAt(linha,3).toString();
           String tempo = tableMusica.getValueAt(linha, 4).toString();
           String ano = tableMusica.getValueAt(linha, 5).toString();
  
           emusicaID.setText(idMusica);
           emusicaNome.setText(nomeMusica);
           emusicaTempo.setText((String) tempo);
           emusicaAno.setText(ano);
           comboboxArtista.setSelectedItem(nomeArtista); 
           selecionaGeneroMusica(generoMusica);
                       
        }
        else  JOptionPane.showMessageDialog(this, "Selecione uma linha!", "ERRO!", JOptionPane.WARNING_MESSAGE);      
    }//GEN-LAST:event_btnSelecionarMusicaActionPerformed

    private void btnExcluirMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMusicaActionPerformed
        try{
            int idMusica = Integer.parseInt(excluiridMusica.getText());
            artistaDAO.descQuantidadeMusica(mySQLConnection, idMusica);
            gerenciadorDAO.deletarMusica(mySQLConnection, idMusica);
            limparCampos();
            tabelaMusica();
        } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Insira um id valido!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirMusicaActionPerformed

    private void btnCadastrarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMusicaActionPerformed
        try{
           music.setNomeMusica(emusicaNome.getText());
           music.setTempoDuracao(Double.parseDouble(emusicaTempo.getText()));
           music.setAno(Integer.parseInt(emusicaAno.getText()));
        
           setGeneroMusica(music);
        
           String auxArtistaNome = (String) comboboxArtista.getSelectedItem();
           music.setnomeArtista(auxArtistaNome);
                
           gerenciadorDAO.insertMusica(mySQLConnection, music);
           artistaDAO.inserirQuantidadeMusica(mySQLConnection, auxArtistaNome);
           limparCampos();
           tabelaMusica();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Os campos Tempo de Duração e Ano devem ser preenchidos com valores numéricos.", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }catch(CampoVazioException e){
            JOptionPane.showMessageDialog(this, "Preencha todo os campos.", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarMusicaActionPerformed

    private void btnAtualizarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarMusicaActionPerformed
        music.setIdMusica(Integer.parseInt(emusicaID.getText()));
        music.setNomeMusica(emusicaNome.getText());  
        music.setTempoDuracao(Double.parseDouble(emusicaTempo.getText()));
        music.setAno(Integer.parseInt(emusicaAno.getText()));
    
        setGeneroMusica(music);
        
        String auxnomeArtita = (String) comboboxArtista.getSelectedItem();
        music.setnomeArtista(auxnomeArtita);
           
        gerenciadorDAO.atualizarMusica(mySQLConnection, music);
        artistaDAO.inserirQuantidadeMusica(mySQLConnection, auxnomeArtita);
        limparCampos();
        tabelaMusica();
    }//GEN-LAST:event_btnAtualizarMusicaActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        try{
            int id = Integer.parseInt(idDelete.getText());
            gerenciadorDAO.deletarUsuario(mySQLConnection, id);
            tabelaUsuarios();
            limparCampos();
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Insira um id valido!", "ERRO!", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Cadastroview cadastroview = new Cadastroview();
        this.dispose();
        cadastroview.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnQtdArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQtdArtistaActionPerformed
        String nomeArtista = (String) comboboxselectArtista.getSelectedItem();
        String quantidade = artistaDAO.quantidadeMusicaArtista(mySQLConnection, nomeArtista);
        quantidadeMusica.setText(quantidade);        
    }//GEN-LAST:event_btnQtdArtistaActionPerformed

    private void btnAdiconarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdiconarArtistaActionPerformed
        String nomeArtista = JOptionPane.showInputDialog(this, "Digine o nome do artista: ", "Artista", JOptionPane.QUESTION_MESSAGE);
        artistaDAO.adicionarNovoArtista(mySQLConnection,nomeArtista);
        comboboxArtista.removeAllItems();
        comboboxselectArtista.removeAllItems();
        comboboxArtista();
    }//GEN-LAST:event_btnAdiconarArtistaActionPerformed
    
    private void comboboxArtista() {
        for (Artista a: artistaDAO.listarArtista(mySQLConnection)) {
            String nome = a.getNomeArtista();
            comboboxArtista.addItem(nome);
            comboboxselectArtista.addItem(nome);
        }
    }    
      
    private void setGeneroMusica(Musica music){
        if(radioEletronica.isSelected())
            music.setGenero(Constants.ELETRONICA);
        else if(radioGospel.isSelected())
            music.setGenero(Constants.GOSPEL);
        else if(radioHiphop.isSelected())
            music.setGenero(Constants.HIP_HOP);
        else if(radioIndie.isSelected())
            music.setGenero(Constants.INDIE);
        else if(radioMpb.isSelected())
            music.setGenero(Constants.MPB);
        else if(radioPagode.isSelected())
            music.setGenero(Constants.PAGODE);
        else if(radioPop.isSelected())
            music.setGenero(Constants.POP);
        else if(radioRock.isSelected())
            music.setGenero(Constants.ROCK);
        else if(radioSertanejo.isSelected())
            music.setGenero(Constants.SERTANEJO);    
        else 
            JOptionPane.showMessageDialog(this, "Selecione o gênero.","Gênero Inválido", JOptionPane.ERROR_MESSAGE);
    }
    
    private void selecionaGeneroMusica(String genero){
        switch (genero) {
            case Constants.ELETRONICA:
                radioEletronica.setSelected(true);
                break;
            case Constants.GOSPEL:
                radioGospel.setSelected(true);
                break;
            case Constants.HIP_HOP:
                radioHiphop.setSelected(true);
                break;
            case Constants.INDIE:
                radioIndie.setSelected(true);
                break;
            case Constants.MPB:
                radioMpb.setSelected(true);
                break;
            case Constants.PAGODE:
                radioPagode.setSelected(true);
                break;
            case Constants.POP:
                radioPop.setSelected(true);
                break;
            case Constants.ROCK:
                radioRock.setSelected(true);
                break;
            case Constants.SERTANEJO:
                radioSertanejo.setSelected(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Gênero inválido","Gênero Inválido", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }
    
    private void tabelaUsuarios(){
        dtmU.setRowCount(0);
 
        for (Usuario usuario : gerenciadorDAO.listarUsuarios(mySQLConnection)){
            dtmU.addRow(new Object[]{
                usuario.getIdUsuario(), usuario.getNomeUsuario(), usuario.getEmail(), usuario.getIdTipoUsuario()
            });
        }
    }
    
    private void tabelaMusica(){
        dtmM.setRowCount(0);
                
        for (Musica musica : gerenciadorDAO.buscarMusicas(mySQLConnection)) {        
            dtmM.addRow(new Object[]{
                musica.getIdMusica(), musica.getNomeMusica(), musica.getnomeArtista(), musica.getGenero(), musica.getTempoDuracao(), musica.getAno()
            });
        }
    }

    
    private void limparCampos() {
        emusicaID.setText("");
        emusicaNome.setText("");
        emusicaTempo.setText("");
        emusicaAno.setText("");
        idDelete.setText("");
        excluiridMusica.setText("");
        quantidadeMusica.setText("");
        buttonGroupGenero.clearSelection();
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdiconarArtista;
    private javax.swing.JButton btnAtualizarMusica;
    private javax.swing.JButton btnCadastrarMusica;
    private javax.swing.JButton btnExcluirMusica;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnQtdArtista;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSelecionarMusica;
    private javax.swing.ButtonGroup buttonGroupGenero;
    private javax.swing.JComboBox<String> comboboxArtista;
    private javax.swing.JComboBox<String> comboboxselectArtista;
    private javax.swing.JLabel eidMusica;
    private javax.swing.JTextField emusicaAno;
    private javax.swing.JTextField emusicaID;
    private javax.swing.JTextField emusicaNome;
    private javax.swing.JTextField emusicaTempo;
    private javax.swing.JTextField excluiridMusica;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JTextField idDelete;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel_Ano;
    private javax.swing.JLabel jLabel_Artista;
    private javax.swing.JLabel jLabel_Artista1;
    private javax.swing.JLabel jLabel_Genero;
    private javax.swing.JLabel jLabel_MUSICAS;
    private javax.swing.JLabel jLabel_NOME;
    private javax.swing.JLabel jLabel_Tempo;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JPanel panelInicial;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelLogin1;
    private javax.swing.JTextField quantidadeMusica;
    private javax.swing.JRadioButton radioEletronica;
    private javax.swing.JRadioButton radioGospel;
    private javax.swing.JRadioButton radioHiphop;
    private javax.swing.JRadioButton radioIndie;
    private javax.swing.JRadioButton radioMpb;
    private javax.swing.JRadioButton radioPagode;
    private javax.swing.JRadioButton radioPop;
    private javax.swing.JRadioButton radioRock;
    private javax.swing.JRadioButton radioSertanejo;
    private javax.swing.JTable tableMusica;
    private javax.swing.JTable tableUsuario;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
