/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Mixer;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.*;

/**
 *
 * @author julin
 */
public class MainFrame extends javax.swing.JFrame {
    Maquina maquina;
    Bebida bebida;
    ArrayList<Thread> threadArray = new ArrayList<Thread>();
    public static boolean usarSemaforo = true;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        maquina = new Maquina();
        initComponents();
        this.setTitle("Coffee Machine");
        this.repaint();
        visorTextArea.setText("Máquina de Café\nEscolha um bebida: ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visorTextArea = new javax.swing.JTextArea();
        nvlCoposProgBar = new javax.swing.JProgressBar();
        nvlCafeProgBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nvlAguaProgBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        nvlLeiteProgBar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        nvlAcucarProgBar = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        nvlChocolateProgBar = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        btnChocolate = new javax.swing.JButton();
        btnCafeLeite = new javax.swing.JButton();
        btnCafe = new javax.swing.JButton();
        btnAgua = new javax.swing.JButton();
        qtdAcucarSlider = new javax.swing.JSlider();
        btnIniciar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        behaviourControlerPanel = new javax.swing.JPanel();
        usarSemaforoBtn = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        btnRecarregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        filaTextArea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(147, 115, 106));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));

        visorTextArea.setBackground(new java.awt.Color(51, 102, 255));
        visorTextArea.setColumns(20);
        visorTextArea.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        visorTextArea.setForeground(new java.awt.Color(255, 255, 255));
        visorTextArea.setLineWrap(true);
        visorTextArea.setRows(3);
        visorTextArea.setText("Máquina de Café");
        visorTextArea.setToolTipText("");
        visorTextArea.setWrapStyleWord(true);
        visorTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        visorTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(visorTextArea);

        nvlCoposProgBar.setBackground(new java.awt.Color(255, 255, 255));
        nvlCoposProgBar.setForeground(new java.awt.Color(0, 255, 0));
        nvlCoposProgBar.setMaximum(50);
        nvlCoposProgBar.setToolTipText("");
        nvlCoposProgBar.setValue(50);
        nvlCoposProgBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nvlCoposProgBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nvlCoposProgBar.setFocusable(false);
        nvlCoposProgBar.setRequestFocusEnabled(false);
        nvlCoposProgBar.setString("Vai pra pqp");
        nvlCoposProgBar.setVerifyInputWhenFocusTarget(false);

        nvlCafeProgBar.setBackground(new java.awt.Color(255, 255, 255));
        nvlCafeProgBar.setForeground(new java.awt.Color(0, 255, 0));
        nvlCafeProgBar.setValue(100);
        nvlCafeProgBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nvlCafeProgBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nvlCafeProgBar.setEnabled(false);
        nvlCafeProgBar.setOpaque(true);
        nvlCafeProgBar.setString("0");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Nível de Açúcar");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Nível de Copos");

        nvlAguaProgBar.setBackground(new java.awt.Color(255, 255, 255));
        nvlAguaProgBar.setForeground(new java.awt.Color(0, 255, 0));
        nvlAguaProgBar.setValue(100);
        nvlAguaProgBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nvlAguaProgBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nvlAguaProgBar.setEnabled(false);
        nvlAguaProgBar.setOpaque(true);
        nvlAguaProgBar.setString("0");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Nível de Água");

        nvlLeiteProgBar.setBackground(new java.awt.Color(255, 255, 255));
        nvlLeiteProgBar.setForeground(new java.awt.Color(0, 255, 0));
        nvlLeiteProgBar.setValue(100);
        nvlLeiteProgBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nvlLeiteProgBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nvlLeiteProgBar.setEnabled(false);
        nvlLeiteProgBar.setOpaque(true);
        nvlLeiteProgBar.setString("0");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Nível de Café");

        nvlAcucarProgBar.setBackground(new java.awt.Color(255, 255, 255));
        nvlAcucarProgBar.setForeground(new java.awt.Color(0, 255, 0));
        nvlAcucarProgBar.setMaximum(50);
        nvlAcucarProgBar.setValue(50);
        nvlAcucarProgBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nvlAcucarProgBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nvlAcucarProgBar.setEnabled(false);
        nvlAcucarProgBar.setString("0");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Nível de Leite");

        nvlChocolateProgBar.setBackground(new java.awt.Color(255, 255, 255));
        nvlChocolateProgBar.setForeground(new java.awt.Color(0, 255, 0));
        nvlChocolateProgBar.setValue(100);
        nvlChocolateProgBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nvlChocolateProgBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nvlChocolateProgBar.setEnabled(false);
        nvlChocolateProgBar.setOpaque(true);
        nvlChocolateProgBar.setString("0");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Nível de Chocolate");

        btnPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnChocolate.setBackground(new java.awt.Color(255, 255, 255));
        btnChocolate.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnChocolate.setForeground(new java.awt.Color(141, 57, 57));
        btnChocolate.setText("Chocolate");
        btnChocolate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChocolateActionPerformed(evt);
            }
        });

        btnCafeLeite.setBackground(new java.awt.Color(255, 255, 255));
        btnCafeLeite.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCafeLeite.setForeground(new java.awt.Color(141, 57, 57));
        btnCafeLeite.setText("Café c Leite");
        btnCafeLeite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCafeLeite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCafeLeiteActionPerformed(evt);
            }
        });

        btnCafe.setBackground(new java.awt.Color(255, 255, 255));
        btnCafe.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCafe.setForeground(new java.awt.Color(141, 57, 57));
        btnCafe.setText("Café");
        btnCafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCafeActionPerformed(evt);
            }
        });

        btnAgua.setBackground(new java.awt.Color(255, 255, 255));
        btnAgua.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAgua.setForeground(new java.awt.Color(141, 57, 57));
        btnAgua.setText("Água");
        btnAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAguaActionPerformed(evt);
            }
        });

        qtdAcucarSlider.setBackground(new java.awt.Color(0, 0, 0));
        qtdAcucarSlider.setForeground(new java.awt.Color(0, 0, 0));
        qtdAcucarSlider.setMaximum(2);
        qtdAcucarSlider.setMinorTickSpacing(1);
        qtdAcucarSlider.setValue(1);
        qtdAcucarSlider.setOpaque(false);
        qtdAcucarSlider.setValueIsAdjusting(true);

        btnIniciar.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel9.setText("Açúcar");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("+");

        imgLabel.setBackground(new java.awt.Color(0, 0, 0));
        imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img1.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("-");

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCafeLeite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgLabel)
                    .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btnPanelLayout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(jLabel9))
                        .addComponent(qtdAcucarSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCafeLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdAcucarSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11))
                    .addGroup(btnPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12)))
                .addGap(24, 24, 24)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        behaviourControlerPanel.setBackground(new java.awt.Color(255, 255, 255));
        behaviourControlerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        usarSemaforoBtn.setBackground(new java.awt.Color(255, 255, 255));
        usarSemaforoBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        usarSemaforoBtn.setForeground(new java.awt.Color(141, 57, 57));
        usarSemaforoBtn.setSelected(true);
        usarSemaforoBtn.setText("Semáforo Ligado");
        usarSemaforoBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usarSemaforoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usarSemaforoBtnActionPerformed(evt);
            }
        });

        consoleTextArea.setBackground(new java.awt.Color(51, 102, 255));
        consoleTextArea.setColumns(20);
        consoleTextArea.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        consoleTextArea.setForeground(new java.awt.Color(255, 255, 255));
        consoleTextArea.setRows(5);
        consoleTextArea.setText("Semáforo -> Ligado");
        consoleTextArea.setToolTipText("");
        consoleTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(consoleTextArea);

        btnRecarregar.setBackground(new java.awt.Color(255, 255, 255));
        btnRecarregar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnRecarregar.setForeground(new java.awt.Color(141, 57, 57));
        btnRecarregar.setText("Recarregar");
        btnRecarregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRecarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout behaviourControlerPanelLayout = new javax.swing.GroupLayout(behaviourControlerPanel);
        behaviourControlerPanel.setLayout(behaviourControlerPanelLayout);
        behaviourControlerPanelLayout.setHorizontalGroup(
            behaviourControlerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(behaviourControlerPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(usarSemaforoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(behaviourControlerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        behaviourControlerPanelLayout.setVerticalGroup(
            behaviourControlerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(behaviourControlerPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(behaviourControlerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usarSemaforoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));

        filaTextArea.setBackground(new java.awt.Color(51, 102, 255));
        filaTextArea.setColumns(20);
        filaTextArea.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        filaTextArea.setForeground(new java.awt.Color(255, 255, 255));
        filaTextArea.setLineWrap(true);
        filaTextArea.setRows(3);
        filaTextArea.setText("Fila:");
        filaTextArea.setToolTipText("");
        filaTextArea.setWrapStyleWord(true);
        filaTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        filaTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(filaTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(nvlAguaProgBar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(nvlCafeProgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(nvlCoposProgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nvlAcucarProgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nvlChocolateProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(nvlLeiteProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(behaviourControlerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nvlCoposProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nvlAcucarProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nvlAguaProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nvlCafeProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nvlChocolateProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nvlLeiteProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(behaviourControlerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCafeActionPerformed
        int acucar = qtdAcucarSlider.getValue();
        String text = "Máquina de Café\nBebida Selecionada: Café\nAçúcar: "+ Integer.toString(acucar);
        visorTextArea.setText(text);
        bebida = new Cafe(acucar);
        String ingredientes = acucar != 0 ? "Café, água e açúcar" : "Café e água";
        Mixer m = new Mixer(maquina.getFilaPreparo(), ingredientes);
        Thread cafeThread = new Thread(m,"Café");
        threadArray.add(cafeThread);
        mostraFila();
    }//GEN-LAST:event_btnCafeActionPerformed

    private void btnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChocolateActionPerformed
        int acucar = qtdAcucarSlider.getValue();
        String text = "Máquina de Café\nBebida Selecionada: Chocolate\nAçúcar: "+ Integer.toString(acucar);
        visorTextArea.setText(text);
        bebida = new Chocolate(acucar);
        String ingredientes = acucar != 0 ? "Chocolate, leite e açúcar" : "Chocolate e leite";
        Mixer m = new Mixer(maquina.getFilaPreparo(), ingredientes);
        Thread chocolateThread = new Thread(m,"Chocolate");
        threadArray.add(chocolateThread);
        mostraFila();
    }//GEN-LAST:event_btnChocolateActionPerformed

    private void btnCafeLeiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCafeLeiteActionPerformed
        int acucar = qtdAcucarSlider.getValue();
        String text = "Máquina de Café\nBebida Selecionada: Café c/ Leite\nAçúcar: "+ Integer.toString(acucar);
        visorTextArea.setText(text);
        bebida = new Pingado(acucar);
        String ingredientes = acucar != 0 ? "Café, leite e açúcar" : "Café e leite";
        Mixer m = new Mixer(maquina.getFilaPreparo(), ingredientes);
        Thread pingadoThread = new Thread(m,"Café com Leite");
        threadArray.add(pingadoThread);
        mostraFila();
    }//GEN-LAST:event_btnCafeLeiteActionPerformed

    private void btnAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAguaActionPerformed
        visorTextArea.setText("Máquina de Café\nBebida Selecionada: Água Quente");
        bebida = new AguaQuente();
        String ingredientes = "Água";
        Mixer m = new Mixer(maquina.getFilaPreparo(), ingredientes);
        Thread aguaQuenteThread = new Thread(m,"Água quente");
        threadArray.add(aguaQuenteThread);
        mostraFila();
    }//GEN-LAST:event_btnAguaActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        for (Thread thread : threadArray) {
            thread.start();
            atualizaMaquina();
        }
        threadArray.clear();
        mostraFila();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void usarSemaforoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usarSemaforoBtnActionPerformed
        usarSemaforo = !usarSemaforo;
        String consoleTextToAppend = usarSemaforo ? "\n\n\nSemáforo -> Ligado" : "\n\n\nSemáforo -> Desligado";
        addSaidaConsole(consoleTextToAppend);
    }//GEN-LAST:event_usarSemaforoBtnActionPerformed

    private void btnRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecarregarActionPerformed
        nvlAguaProgBar.setValue(100);
        nvlAcucarProgBar.setValue(50);
        nvlCafeProgBar.setValue(100);
        nvlChocolateProgBar.setValue(100);
        nvlCoposProgBar.setValue(50);
        nvlLeiteProgBar.setValue(100);
    }//GEN-LAST:event_btnRecarregarActionPerformed
    
    public static void addSaidaConsole(String consoleTextToAppend){
        try {
            String textInConsole = consoleTextArea.getText();
            consoleTextArea.setText(textInConsole.concat(consoleTextToAppend));
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static boolean getSemaphoreState(){
        return usarSemaforo;
    }
    
    private void mostraFila(){
        String filaText = "Fila:\n";
        for (Thread thread : threadArray) {
            filaText+="[ ";
            filaText+=thread.getName();
            filaText+=" ], ";
        }
        filaTextArea.setText(filaText);
    }
    
    private void atualizaMaquina(){
        bebida.executar(bebida, maquina);
        nvlAguaProgBar.setValue(maquina.getNivelAgua());
        nvlAcucarProgBar.setValue(maquina.getNivelAçucar());
        nvlCafeProgBar.setValue(maquina.getNivelCafe());
        nvlChocolateProgBar.setValue(maquina.getNivelChocolate());
        nvlCoposProgBar.setValue(maquina.getNivelCopo());
        nvlLeiteProgBar.setValue(maquina.getNivelLeite());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel behaviourControlerPanel;
    private javax.swing.JButton btnAgua;
    private javax.swing.JButton btnCafe;
    private javax.swing.JButton btnCafeLeite;
    private javax.swing.JButton btnChocolate;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnRecarregar;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextArea consoleTextArea;
    private javax.swing.JTextArea filaTextArea;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JProgressBar nvlAcucarProgBar;
    private javax.swing.JProgressBar nvlAguaProgBar;
    private javax.swing.JProgressBar nvlCafeProgBar;
    private javax.swing.JProgressBar nvlChocolateProgBar;
    private javax.swing.JProgressBar nvlCoposProgBar;
    private javax.swing.JProgressBar nvlLeiteProgBar;
    private javax.swing.JSlider qtdAcucarSlider;
    private javax.swing.JToggleButton usarSemaforoBtn;
    private javax.swing.JTextArea visorTextArea;
    // End of variables declaration//GEN-END:variables
}
