/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DentistaController;
import controller.ArquivoController;
import exception.DocumentoVazioException;
import exception.NomeVazioException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Dentista;

/**
 *
 * @author julia
 */
public class Cadastroview extends javax.swing.JFrame {

    /**
     * Creates new form Cadastroview
     */
    
    DefaultTableModel dtm;
    
    public Cadastroview() {
        initComponents();
        this.setName("Rede de Dentistas");
        this.setLocationRelativeTo(null);
        dtm = (DefaultTableModel) table_Dentista.getModel();
        ler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_Especialidade = new javax.swing.ButtonGroup();
        panelCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_Nome = new javax.swing.JTextField();
        tf_Telefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_Documento = new javax.swing.JTextField();
        tf_CRO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_Avaliacao = new javax.swing.JTextField();
        rb_Cirurgia = new javax.swing.JRadioButton();
        rb_Clinica = new javax.swing.JRadioButton();
        rb_Dentistica = new javax.swing.JRadioButton();
        btn_Cadastrar = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        panelDentistas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Dentista = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        numDent = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        numero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelCadastro.setBackground(new java.awt.Color(255, 255, 255));
        panelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N
        panelCadastro.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        jLabel1.setText("Nome");

        jLabel2.setText("Telefone");

        tf_Nome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tf_Nome.setToolTipText("");

        tf_Telefone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel3.setText("Documento");

        tf_Documento.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        tf_CRO.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel4.setText("Especialidade");

        jLabel5.setText("CRO");

        jLabel6.setText("Avaliação");

        tf_Avaliacao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        rb_Cirurgia.setBackground(new java.awt.Color(0, 255, 255));
        bg_Especialidade.add(rb_Cirurgia);
        rb_Cirurgia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_Cirurgia.setText("Cirurgia");

        rb_Clinica.setBackground(new java.awt.Color(0, 255, 255));
        bg_Especialidade.add(rb_Clinica);
        rb_Clinica.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_Clinica.setText("Clinica Geral");

        rb_Dentistica.setBackground(new java.awt.Color(0, 255, 255));
        bg_Especialidade.add(rb_Dentistica);
        rb_Dentistica.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rb_Dentistica.setText("Dentistica");

        btn_Cadastrar.setBackground(new java.awt.Color(0, 255, 255));
        btn_Cadastrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Cadastrar.setText("CADASTRAR");
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_Limpar.setBackground(new java.awt.Color(0, 255, 255));
        btn_Limpar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Limpar.setText("LIMPAR");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(tf_CRO, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Avaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addComponent(rb_Cirurgia)
                        .addGap(18, 18, 18)
                        .addComponent(rb_Clinica)
                        .addGap(18, 18, 18)
                        .addComponent(rb_Dentistica)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addComponent(btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_Cirurgia)
                            .addComponent(rb_Clinica)
                            .addComponent(rb_Dentistica))
                        .addGap(18, 18, 18)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_CRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Avaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelDentistas.setBackground(new java.awt.Color(255, 255, 255));
        panelDentistas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dentistas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16))); // NOI18N

        table_Dentista.setAutoCreateRowSorter(true);
        table_Dentista.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        table_Dentista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Documento", "CRO", "Telefone", "Especialidade", "Avaliação"
            }
        ));
        table_Dentista.setGridColor(new java.awt.Color(0, 255, 255));
        jScrollPane1.setViewportView(table_Dentista);

        jLabel7.setText("Numero de Dentistas: ");

        numDent.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("LISTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        numero.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        numero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelDentistasLayout = new javax.swing.GroupLayout(panelDentistas);
        panelDentistas.setLayout(panelDentistasLayout);
        panelDentistasLayout.setHorizontalGroup(
            panelDentistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panelDentistasLayout.createSequentialGroup()
                .addGroup(panelDentistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDentistasLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(numDent)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDentistasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(numero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panelDentistasLayout.setVerticalGroup(
            panelDentistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDentistasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelDentistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDentistasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDentistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(numDent)
                            .addComponent(numero))
                        .addGap(33, 33, 33))
                    .addGroup(panelDentistasLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDentistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelDentistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        String nome = tf_Nome.getText();
        String documento = tf_Documento.getText();
        String cro = tf_CRO.getText();
        long telefone = Long.parseLong(tf_Telefone.getText());
        int avaliacao = Integer.parseInt(tf_Avaliacao.getText());
        
        String especialidade = null;
        if(rb_Clinica.isSelected()){
            especialidade = "Clinica Geral";
        }else if(rb_Cirurgia.isSelected()){
            especialidade = "Cirurgia";
        }else if(rb_Dentistica.isSelected()){
            especialidade = "Dentistica";
        }
        
        try {
            DentistaController.salvarDentista(nome, documento, cro, telefone, especialidade, avaliacao);
            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso", "Rede de Dentistas", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
        }catch (NomeVazioException e) {
            JOptionPane.showMessageDialog(this, "Nome", "Campo Vazio", JOptionPane.ERROR_MESSAGE);
        }catch (DocumentoVazioException e){
            JOptionPane.showMessageDialog(this, "Documento", "Campo Vazio", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ler();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void limparCampos() {
        tf_Nome.setText("");
        tf_Telefone.setText("");
        tf_Documento.setText("");
        tf_CRO.setText("");
        tf_Avaliacao.setText("");
        bg_Especialidade.clearSelection();
    }
    
    private void ler(){
        dtm.setRowCount(0);
        for (Dentista dentista : ArquivoController.listarDentistas()) {
            dtm.addRow(new Object[]{
                dentista.getNome(), dentista.getDocumento(), dentista.getCro(), dentista.getTelefone(), dentista.getEspecialidade(), dentista.getAvaliacao()
            });
        };
        numero.setText(Integer.toString(dtm.getRowCount()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastroview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Especialidade;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numDent;
    private javax.swing.JLabel numero;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JPanel panelDentistas;
    private javax.swing.JRadioButton rb_Cirurgia;
    private javax.swing.JRadioButton rb_Clinica;
    private javax.swing.JRadioButton rb_Dentistica;
    private javax.swing.JTable table_Dentista;
    private javax.swing.JTextField tf_Avaliacao;
    private javax.swing.JTextField tf_CRO;
    private javax.swing.JTextField tf_Documento;
    private javax.swing.JTextField tf_Nome;
    private javax.swing.JTextField tf_Telefone;
    // End of variables declaration//GEN-END:variables
}
